### ISSUE TITLE
how to add other languages

### ISSUE THREAD

**Issue by 17lwinn** [baseapp/liveide#11]
how do we add new langauges?

**Comment by vsergeyev** [comment]
Hello @17lwinn 

Thank you for your interest.
Right now Python is hardcoded in https://github.com/baseapp/liveide/blob/master/ide/static/js/liveide.js#L301

My understanding it should be added a menu with a list of languages to choose.

Regards,
V.

**Comment by 17lwinn** [comment]
okay thanks!
