### ISSUE TITLE
Copy project

### ISSUE THREAD

**Issue by ntavish** [baseapp/liveide#7]
If we need to have samples/templates for projects, we need to be able to copy project folders from inside liveide. This should be a simple 'cp -r' with a new directory(project) name.

**Comment by ntavish** [comment]
Option in 'Project settings' to mark project and contents as read-only should be enough to make it a Template/Sample.

**Comment by vsergeyev** [comment]
Copy Project added in https://github.com/baseapp/liveide/commit/7143766f6d917a8ea92a91ac34602ceb83687bd6
Please QA

**Comment by ntavish** [comment]
Closing issue. Now we can just include sample/template project directories with liveide, and user can copy them to their own project root.
